### ISSUE TITLE
Provider duplicated when login with facebook

### ISSUE THREAD

**Issue by dadaxr** [bolt/Members#18]
each time in log into with facebook ( same user ), a new row is inserted in bolt_members_provider table.

Seems a bug to me :)

**Comment by GawainLynch** [comment]
Yeah, new bug from something I tweaked a few days ago.

**Comment by GawainLynch** [comment]
Just looking at it, it looks like it might have been fixed… but is caused by a bad provider record… flushing them gets  back to normal for me.

Could you let me know.

**Comment by dadaxr** [comment]
Ok so i've just checked, the bug is still there.

I updated to the latest version ( 284868884b6c2f1b0441e8632bb8b60aeb7298a0 ) to be sure, then empty the different bolt_members_xxx tables. Then Sign in with facebook. 
1 row inserted in : 
bolt_members_provider, bolt_members_token and bolt_members_account.
Then logout, login back with facebook... and ..
1 more row in bolt_members_provider... ( other tables still have just one )
Moreover the row added is exactly the same 

The other weird thing is that there is a unique Mysql Key on columns "provider, resource_owner_id", and despite of that i get thoses 2 rows : 

`
1	469b6def-4820-45cc-8f00-a89552c93d30	facebook			{ truncated json }	2016-04-13 20:20:05

2	469b6def-4820-45cc-8f00-a89552c93d30	facebook			{ troncated json }	2016-04-13 20:20:55
`

Got an idea ? Oauth stuff is quite a complexe stuff i dont dig into code too much yet.

**Comment by dadaxr** [comment]
Found the bug : 
when saving the provider entity the first time, the RessourceOwner is set but not the RessourceOwnerId... too bad ;)

file : <project_root>\extensions\vendor\bolt\members\src\Oauth2\Handler\AbstractHandler.php, line 224

`
$this->providerEntity = new Entity\Provider();
        $this->providerEntity->setGuid($account->getGuid());
        $this->providerEntity->setProvider($providerName);
        $this->providerEntity->setResourceOwner($resourceOwner);
        $this->providerEntity->setLastupdate(Carbon::now());
`

adding : 

`
$this->providerEntity->setResourceOwnerId($resourceOwner->getId());
`

does the job :)

**Comment by GawainLynch** [comment]
Thanks very much!

Fixed in 5f2b495
